# Generated by Django 5.2.6 on 2025-09-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('region', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField(help_text='Days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='tours/')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
