# Generated by Django 5.2.6 on 2025-09-25 18:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tour_alter_review_content_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='detailed_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
