# Generated by Django 5.2.6 on 2025-09-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tour_detailed_info_alter_tour_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-id'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'Tour Image', 'verbose_name_plural': 'Tour Images'},
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
